### ISSUE TITLE
Build a backend

### ISSUE THREAD

**Issue by nzec** [Ploypiti/mysic#1]
* Technologies to be added : 

  * Node.js, Express.js (for basic web server backend)
  * body-parser (adds the `req.body` method that is helpful af)
  * Need to implement some kind of sessions to make a proper authentication system (express-sessions) and also a properly hash passwords (bcrypt maybe?)
  * Need some kind of a database? SQL or Mongo? I am pretty okay with Mongo.

---
I had made an authentication system here : https://github.com/duttaditya18/learn-node-js/tree/master/bookworm

I would really like to work on this, because I am really bored and none of my friends want to do some projects :(

**Comment by Ploypiti** [comment]
Thanks for the first issue XD
To be honest, I planned to use firebase since it has auth management, angularjs integration and kinds of stuff, anyway _if_ you happen to be working on database feel free to use whatever you want. Oh, also, welcome to my little world of unformatted code.

**Comment by nzec** [comment]
@Ploypiti Awesome! I'll start working!

Issues do come fast don't they? 😄

**Comment by nzec** [comment]
This seems to be almost done by @nisaruj

**Comment by Ploypiti** [comment]
@duttaditya18 Sorry bout that (｡-_-｡) Anyway, it turns out we (or just him?) made a few of _mistakes_ indeed, so yeah, _maybe_ _if_ you wanna improve something feel free to do so. :D
